import React from 'react';


const Navbar = () => {
  let link =
  'http://cdn.shopify.com/s/files/1/2114/5389/products/wood_backdrop_medium_backdrop_boards_medium_backdrops_grande.jpg?v=1521740229';
  let link2 =
  'http://biteinto.info/wp-content/uploads/2016/02/light-wood-grain-background-and-keywords-wooden-texture-surface-backdrop-hard-wood-grain-smooth-planed-19.jpg';
  let link3 =
  'https://img.etsystatic.com/il/27099a/1393512158/il_fullxfull.1393512158_p77c.jpg?version=0';
  let beach =
  'http://blog.tours4fun.com/wp-content/uploads/2018/03/shimizu.jpg';
  let rest =
  'http://www.pngall.com/wp-content/uploads/2016/03/Macaw-High-Quality-PNG.png';
  let spacedrop =
  'https://upload.wikimedia.org/wikipedia/commons/1/10/MA_illustration_2016_17_%2824523577579%29.jpg';
  const spaceship = ''



  return (
    <div className="navbar">
      <img className="background" src={spacedrop}></img>
      <section>
        <h1 id='nombre'>ReweL</h1>
      </section>
      <div className="title"></div>
      <img src='../../../assets/images/space0.png'></img>
      <div id="name">ReweL</div>
      <p>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce aliquam vestibulum ipsum. Quisque tincidunt scelerisque libero. Pellentesque ipsum. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Curabitur vitae diam non enim vestibulum interdum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Fusce tellus. Integer tempor. Nam sed tellus id magna elementum tincidunt. Mauris metus. Nulla quis diam. Nullam sit amet magna in magna gravida vehicula. Fusce tellus.

Phasellus rhoncus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Pellentesque ipsum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam posuere lacus quis dolor. Nulla non lectus sed nisl molestie malesuada. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Aliquam erat volutpat. Suspendisse nisl. Pellentesque ipsum. Praesent dapibus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer pellentesque quam vel velit.

Quisque porta. Cras elementum. Mauris metus. Mauris elementum mauris vitae tortor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aliquam in lorem sit amet leo accumsan lacinia. Fusce suscipit libero eget elit. Etiam bibendum elit eget erat. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Maecenas libero. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nam quis nulla. Nunc dapibus tortor vel mi dapibus sollicitudin. Fusce aliquam vestibulum ipsum. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla non lectus sed nisl molestie malesuada.

Maecenas libero. Vivamus porttitor turpis ac leo. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis pulvinar. Integer vulputate sem a nibh rutrum consequat. Nullam faucibus mi quis velit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Mauris dictum facilisis augue. Aenean id metus id velit ullamcorper pulvinar. Donec iaculis gravida nulla.

Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque ipsum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin in tellus sit amet nibh dignissim sagittis. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Duis viverra diam non justo. Praesent id justo in neque elementum ultrices. Fusce wisi. Curabitur vitae diam non enim vestibulum interdum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aliquam erat volutpat.

      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce aliquam vestibulum ipsum. Quisque tincidunt scelerisque libero. Pellentesque ipsum. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Curabitur vitae diam non enim vestibulum interdum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Fusce tellus. Integer tempor. Nam sed tellus id magna elementum tincidunt. Mauris metus. Nulla quis diam. Nullam sit amet magna in magna gravida vehicula. Fusce tellus.

Phasellus rhoncus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Pellentesque ipsum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam posuere lacus quis dolor. Nulla non lectus sed nisl molestie malesuada. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Aliquam erat volutpat. Suspendisse nisl. Pellentesque ipsum. Praesent dapibus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer pellentesque quam vel velit.

Quisque porta. Cras elementum. Mauris metus. Mauris elementum mauris vitae tortor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aliquam in lorem sit amet leo accumsan lacinia. Fusce suscipit libero eget elit. Etiam bibendum elit eget erat. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Maecenas libero. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nam quis nulla. Nunc dapibus tortor vel mi dapibus sollicitudin. Fusce aliquam vestibulum ipsum. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla non lectus sed nisl molestie malesuada.

Maecenas libero. Vivamus porttitor turpis ac leo. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis pulvinar. Integer vulputate sem a nibh rutrum consequat. Nullam faucibus mi quis velit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Mauris dictum facilisis augue. Aenean id metus id velit ullamcorper pulvinar. Donec iaculis gravida nulla.

Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque ipsum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin in tellus sit amet nibh dignissim sagittis. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Duis viverra diam non justo. Praesent id justo in neque elementum ultrices. Fusce wisi. Curabitur vitae diam non enim vestibulum interdum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aliquam erat volutpat.

      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce aliquam vestibulum ipsum. Quisque tincidunt scelerisque libero. Pellentesque ipsum. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Curabitur vitae diam non enim vestibulum interdum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Fusce tellus. Integer tempor. Nam sed tellus id magna elementum tincidunt. Mauris metus. Nulla quis diam. Nullam sit amet magna in magna gravida vehicula. Fusce tellus.

Phasellus rhoncus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Pellentesque ipsum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam posuere lacus quis dolor. Nulla non lectus sed nisl molestie malesuada. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Aliquam erat volutpat. Suspendisse nisl. Pellentesque ipsum. Praesent dapibus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer pellentesque quam vel velit.

Quisque porta. Cras elementum. Mauris metus. Mauris elementum mauris vitae tortor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aliquam in lorem sit amet leo accumsan lacinia. Fusce suscipit libero eget elit. Etiam bibendum elit eget erat. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Maecenas libero. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nam quis nulla. Nunc dapibus tortor vel mi dapibus sollicitudin. Fusce aliquam vestibulum ipsum. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla non lectus sed nisl molestie malesuada.

Maecenas libero. Vivamus porttitor turpis ac leo. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis pulvinar. Integer vulputate sem a nibh rutrum consequat. Nullam faucibus mi quis velit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Mauris dictum facilisis augue. Aenean id metus id velit ullamcorper pulvinar. Donec iaculis gravida nulla.

Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque ipsum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin in tellus sit amet nibh dignissim sagittis. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Duis viverra diam non justo. Praesent id justo in neque elementum ultrices. Fusce wisi. Curabitur vitae diam non enim vestibulum interdum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aliquam erat volutpat.

      </p>
      <p>
      Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce aliquam vestibulum ipsum. Quisque tincidunt scelerisque libero. Pellentesque ipsum. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Curabitur vitae diam non enim vestibulum interdum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Fusce tellus. Integer tempor. Nam sed tellus id magna elementum tincidunt. Mauris metus. Nulla quis diam. Nullam sit amet magna in magna gravida vehicula. Fusce tellus.

Phasellus rhoncus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Pellentesque ipsum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam posuere lacus quis dolor. Nulla non lectus sed nisl molestie malesuada. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Aliquam erat volutpat. Suspendisse nisl. Pellentesque ipsum. Praesent dapibus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer pellentesque quam vel velit.

Quisque porta. Cras elementum. Mauris metus. Mauris elementum mauris vitae tortor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aliquam in lorem sit amet leo accumsan lacinia. Fusce suscipit libero eget elit. Etiam bibendum elit eget erat. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Maecenas libero. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nam quis nulla. Nunc dapibus tortor vel mi dapibus sollicitudin. Fusce aliquam vestibulum ipsum. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla non lectus sed nisl molestie malesuada.

Maecenas libero. Vivamus porttitor turpis ac leo. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis pulvinar. Integer vulputate sem a nibh rutrum consequat. Nullam faucibus mi quis velit. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Mauris dictum facilisis augue. Aenean id metus id velit ullamcorper pulvinar. Donec iaculis gravida nulla.

Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque ipsum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin in tellus sit amet nibh dignissim sagittis. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Duis viverra diam non justo. Praesent id justo in neque elementum ultrices. Fusce wisi. Curabitur vitae diam non enim vestibulum interdum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aliquam erat volutpat.

      </p>
    </div>
  );
};

// <img src={spacedrop}></img>
// <img src={beach}></img>
export default Navbar;
